[project]
name = "ice-whisper"
version = "0.1.0"
description = "This project focuses on improving the performance of OpenAI's Whisper Large v3 model for Icelandic speech recognition by fine-tuning it on the Raddrómur Icelandic Speech corpus using Parameter-Efficient Fine-Tuning (PEFT) with LoRA. The fine-tuned model is then evaluated against the base model on a subset of the Samrómur Milljón dataset."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "accelerate==1.6.0",
    "aiohappyeyeballs==2.6.1",
    "aiohttp==3.11.18",
    "aiosignal==1.3.2",
    "annotated-types==0.7.0",
    "asttokens==3.0.0",
    "async-timeout==5.0.1",
    "attrs==25.3.0",
    "audioread==3.0.1",
    "bitsandbytes==0.45.5",
    "certifi==2025.4.26",
    "cffi==1.17.1",
    "charset-normalizer==3.4.1",
    "click==8.1.8",
    "comm==0.2.2",
    "contourpy==1.3.2",
    "cycler==0.12.1",
    "datasets==3.5.1",
    "debugpy==1.8.14",
    "decorator==5.2.1",
    "dill==0.3.8",
    "docker-pycreds==0.4.0",
    "dotenv==0.9.9",
    "evaluate==0.4.3",
    "exceptiongroup==1.2.2",
    "executing==2.2.0",
    "filelock==3.18.0",
    "fonttools==4.57.0",
    "frozenlist==1.6.0",
    "fsspec==2025.2.0",
    "gitdb==4.0.12",
    "gitpython==3.1.44",
    "huggingface-hub==0.30.2",
    "idna==3.10",
    "ipykernel==6.29.5",
    "ipython==8.36.0",
    "ipywidgets==8.1.7",
    "jedi==0.19.2",
    "jinja2==3.1.6",
    "jiwer==3.1.0",
    "joblib==1.4.2",
    "jupyter-client==8.6.3",
    "jupyter-core==5.7.2",
    "jupyterlab-widgets==3.0.15",
    "kiwisolver==1.4.8",
    "lazy-loader==0.4",
    "librosa==0.11.0",
    "llvmlite==0.44.0",
    "markupsafe==3.0.2",
    "matplotlib==3.10.1",
    "matplotlib-inline==0.1.7",
    "mpmath==1.3.0",
    "msgpack==1.1.0",
    "multidict==6.4.3",
    "multiprocess==0.70.16",
    "nest-asyncio==1.6.0",
    "networkx==3.4.2",
    "ninja==1.11.1.4",
    "numba==0.61.2",
    "numpy==2.2.5",
    "nvidia-cublas-cu12==12.6.4.1",
    "nvidia-cuda-cupti-cu12==12.6.80",
    "nvidia-cuda-nvrtc-cu12==12.6.77",
    "nvidia-cuda-runtime-cu12==12.6.77",
    "nvidia-cudnn-cu12==9.5.1.17",
    "nvidia-cufft-cu12==11.3.0.4",
    "nvidia-cufile-cu12==1.11.1.6",
    "nvidia-curand-cu12==10.3.7.77",
    "nvidia-cusolver-cu12==11.7.1.2",
    "nvidia-cusparse-cu12==12.5.4.2",
    "nvidia-cusparselt-cu12==0.6.3",
    "nvidia-nccl-cu12==2.26.2",
    "nvidia-nvjitlink-cu12==12.6.85",
    "nvidia-nvtx-cu12==12.6.77",
    "packaging==25.0",
    "pandas==2.2.3",
    "parso==0.8.4",
    "peft==0.15.2",
    "pexpect==4.9.0",
    "pillow==11.2.1",
    "platformdirs==4.3.7",
    "pooch==1.8.2",
    "prompt-toolkit==3.0.51",
    "propcache==0.3.1",
    "protobuf==6.30.2",
    "psutil==7.0.0",
    "ptyprocess==0.7.0",
    "pure-eval==0.2.3",
    "pyarrow==20.0.0",
    "pycparser==2.22",
    "pydantic==2.11.4",
    "pydantic-core==2.33.2",
    "pygments==2.19.1",
    "pyparsing==3.2.3",
    "python-dateutil==2.9.0.post0",
    "python-dotenv==1.1.0",
    "pytz==2025.2",
    "pyyaml==6.0.2",
    "pyzmq==26.4.0",
    "rapidfuzz==3.13.0",
    "regex==2024.11.6",
    "requests==2.32.3",
    "safetensors==0.5.3",
    "scikit-learn==1.6.1",
    "scipy==1.15.2",
    "sentry-sdk==2.27.0",
    "setproctitle==1.3.6",
    "setuptools==80.0.1",
    "six==1.17.0",
    "smmap==5.0.2",
    "soundfile==0.13.1",
    "soxr==0.5.0.post1",
    "stack-data==0.6.3",
    "sympy==1.14.0",
    "threadpoolctl==3.6.0",
    "tokenizers==0.21.1",
    "torch==2.7.0",
    "torchaudio==2.7.0",
    "tornado==6.4.2",
    "tqdm==4.67.1",
    "traitlets==5.14.3",
    "transformers==4.51.3",
    "triton==3.3.0",
    "typing-extensions==4.13.2",
    "typing-inspection==0.4.0",
    "tzdata==2025.2",
    "urllib3==2.4.0",
    "wandb==0.19.10",
    "wcwidth==0.2.13",
    "widgetsnbextension==4.0.14",
    "xxhash==3.5.0",
    "yarl==1.20.0",
]
